version: "3"

services:
  frontend:
    image: node:12.16.3
    ports:
      - "3000:3000"
    volumes:
      - './frontend:/myapp'
    working_dir: /myapp
    command: /bin/sh -c "npm start"
    tty: true
    stdin_open: true

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./backend:/backend
      - bundle:/usr/local/bundle

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: backend_development
      MYSQL_USER: rails
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql-data:
  bundle:
